version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "sam-app-production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mmymwsf71w07"
s3_prefix = "sam-app-production"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Stage=production"

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "sam-app-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mmymwsf71w07"
s3_prefix = "sam-app-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Stage=staging"
